- meta/main.yml
the mariadb dependecy installs a mariadb server by default which is not needed if you use an external database like azure DB
> remove mariadb dependency

- templates/etc/icinga2/features-available/ido-mysql.conf.j2
```
--- before: /etc/icinga2/features-available/ido-mysql.conf
+++ after: /etc/icinga2/features-available/ido-mysql.conf
@@ -13,5 +13,5 @@
password = "YPSt5rPTC3dfY9SxsiSx6jVNL9mQagCy"
host = "db-adsy-monitoring-prod-westeurope-1.mysql.database.azure.com"
database = "icinga2"
-    enable_ssl = true
+  enable_ssl = true
}
```
> fix indentation of enable_ssl in ido configuration

- templates/etc/icinga2/zones.d/global-templates/services.conf.j2
This change allows us to make the procs command configurable per host. Example config:
```c
vars.procs["procs"] = {
procs_warning = 512
procs_critical = 1024
}
vars.procs["dockerd-current"] = {
procs_command = "dockerd-current"
procs_warning = "1:1"
procs_critical = "1:1"
}
```
This config piece monitors the process count with modified warning and critical values. It has also another section for checking if a docker process is running.
> make procs Service configurable per host

- tasks/configuration.yml
This should help after upgrading icinga2 when the files are recreated from the package and icinga2 complains about doubled objects
> make the ununused conf files empty instead of deleting

- templates/etc/icinga2/zones.d/global-templates/services.conf.j2
This change implements the following new service apply rules:
* imap
* smtp
* ldap
* redis
Below is an example on how to use these apply rules. The available variables can be taken from the official [icinga template library](https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#mysql).
```
icinga2_vars:
- name: 'vars.imap_hosts["imaps"]'
value: |
{
imap_port = 993
imap_ssl = true
}
- name: 'vars.imap_hosts["imap"]'
value: |
{
imap_port = 143
}
```
> services: imap, smtp, ldap and redis

- templates/etc/icinga2/zones.d/global-templates/services.conf.j2
This change adds the necessary sections in `/etc/icinga2/zones.d/global-templates/services.conf` to apply the checks for `check_tcp` and `check_tcp`.
```
ansible 2.7.10
configured module search path = ['/home/andi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.7/site-packages/ansible
python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
```
Below is an example on how to use these apply rules. The available variables can be taken from the official [icinga template library](https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#tcp).
```
icinga2_vars:
- name: 'vars.tcp_checks["tcp/8074 …
```
> Add tcp/udp checks

- tasks/installation.yml
icinga2_master_register_icinga2_imported.rc is not defined when icinga2_master_ido_enabled is set to false. So first check if this is set to true and after that evaluating the second variable is a good idea.
```
ansible 2.7.10
configured module search path = ['/home/tr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.7/site-packages/ansible
python version = 3.7.3 (default, Mar 27 2019, 13:41:07) [GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
```
> Undefined variable.

- templates/etc/icinga2/zones.d/global-templates/services.conf.j2
This change amends the [by_ssh](https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#by_ssh) check to the global template.
```
ansible 2.8.1
configured module search path = ['/home/andi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.7/site-packages/ansible
python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
```
> add by_ssh check to global template

- tasks/configuration.yml
- templates/etc/icinga2/zones.d/generic_host_without_ping.conf.j2
- templates/etc/icinga2/zones.d/global-templates/services.conf.j2
I added mechanics to support satellites that are not reachable from the internet.
The playbook currently does create a satellite config that DOES work without reachability from outside but ping4, ping6 and check_command == "checkalive" does not work like that.
The commit changes check_command to "icinga" when the host is in the  [monitoring-sat] group.
Also, the service-template does not apply ping4 and ping6 checks to hosts with that setting anymore.
Commits will be squashed at merge.
> Update mechanics to support satellites which are not directly reachable

- templates/etc/icinga2/zones.d/generic_host.conf.j2
This allows us to use other `check_commands` like `icinga2` or `dummy` if the host is not reachable through ICMP.
> implement check_command variable

- templates/etc/icinga2/zones.d/global-templates/services.conf.j2
Changed load to percpu mechanism
Changed load to percpu mechanism (Every host is a 1CPU Host, so a 0.90 load is 90% workload, so warning!)
```
No additional information, dnsmichi
```
> Fixxed the load check 

- README.md
- templates/etc/icinga2/scripts/twilio-phone-notification.sh.j2
Currently, our setup generates a new error email as we do not have a TwiML application configured. Twilio has recently implement TwiML Bin which means we can now create TwiML application in their portal and do not have to self-host them. But these are only available through an url (as far as I understand it).
```
```
```
```
> feat(twilio_phone): allow application sid or application url

- tasks/configuration.yml
In ansible 2.10, TRANSFORM_INVALID_GROUP_CHARS will change and not allow dashes in group names anymore
```
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in
group names by default, this will change, but still be user configurable on deprecation. This
feature will be removed in version 2.10.
```
BREAKING CHANGE: groups in the playbook must be renamed
```
ansible 2.8.5
configured module search path = ['/home/fujexo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.7/site-packages/ansible
python version = 3.7.5 (default, Oct 17 2019, 12:16:48) [GCC 9.2.1 20190827 (Red Hat …
```
> fix(ansible groups): groups names containing a dash (-) are invalid

- tasks/installation.yml
In check mode, there is no task result to be stored in the register `icinga2_master_register_icinga2_imported`, so the `rc` field is missing. Subsequent checks that rely on the field existing therefore fail.
Since the same task sets the `changed` property if `rc` is 1, we can use that field instead, as it is guaranteed to exist, and we essentially perform the same check down the line.
```
ansible 2.8.1
configured module search path = [u'/home/martinwe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/dist-packages/ansible
python version = 2.7.9 (default, Sep 25 2018, 20:42:16) [GCC 4.9.2]
```
```
TASK …
```
> tasks/installation.yml: Don't use rc register field in check mode

- templates/etc/icinga2/conf.d/templates.conf.j2
This PR adds missing basic templates for hosts, services and users.
These templates are part of the [upstream `templates.conf`](https://github.com/Icinga/icinga2/blob/master/etc/icinga2/conf.d/templates.conf).
This fixes issue #74.
```
ansible 2.9.6
config file = None
configured module search path = ['/Users/christian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible
python version = 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) [Clang 6.0 (clang-600.0.57)]
```
See also issue #74.
**Before**
```
RUNNING HANDLER [adfinis-sygroup.icinga2_master : …
```
> add missing templates (see also issue #74)

- tasks/configuration.yml
- vars/Debian.yml
- vars/RedHat.yml
This PR adds variables for Debian/RedHat to set the appropriate configuration file owner/group.
See also issue #72 .
```
ansible 2.9.6
config file = None
configured module search path = ['/Users/christian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible
python version = 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) [Clang 6.0 (clang-600.0.57)]
```
See also issue #72.
**Before change**
```
TASK [adfinis-sygroup.icinga2_master : install icinga2 configuration] *************************************************************************************** …
```
> change configuration file owners for Debian

- tasks/configuration.yml
- templates/etc/icinga2/zones.conf.j2
Write satellite zone configs to global zones.conf instead of writing them to a file within the parent's zones.d directory.
As described in https://github.com/Icinga/icinga2/issues/7530:
> 2.11 hardens the config sync thus only including directories in zones.d which have been configured outside in zones.conf.
The current configuration of satellites does not work anymore with icinga2 >= 2.11. To make this work satellite zones have to be defined in the global `zones.conf`.
> Write satellite zone configs to global zones.conf

- templates/etc/icinga2/zones.d/generic_zone.conf.j2
Prevent icinga2 from attempting to connect to dummy hosts
```
critical/ApiListener: Cannot connect to host 'foo.bar.example.com' on port '5665': Host not found (authoritative)
```
> Prevent icinga2 from attempting to connect to dummy hosts

- tasks/configuration.yml
Set proper permissions for conf.d/services.conf & conf.d/hosts.conf
> Set proper permissions for conf.d/services.conf & conf.d/hosts.conf

- README.md
- defaults/main.yml
- tasks/configuration.yml
- templates/etc/icinga2/conf.d/downtimes.conf.j2
Icinga2 Director does not provide any functionality to set recurring downtimes, so modifying the configuration directly is necessary for this.
This allows setting downtimes for a given set of services on a given set of hosts.
```
ansible 2.9.4
configured module search path = [u'/home/{{user}}/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/dist-packages/ansible
python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```
> Add downtimes.conf template

- README.md
- defaults/main.yml
- templates/etc/icinga2/conf.d/downtimes.conf.j2
This is a follow-up to #95, to allow downtimes to be set on hosts, too.
The template is adapted to apply a downtime to `Host` instead of `Service` (and without any `where` clause for service names) if the `services:` attribute in a downtime specification is unset or empty.
See also [this example](https://community.icinga.com/t/schedule-downtimes-for-hosts/3472/2) for a reference.
```
ansible 2.9.4
configured module search path = [u'/home/{{user}}/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/dist-packages/ansible
python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```
Not fully tested yet; but validity …
> Allow downtimes to be set on hosts

- README.md
- defaults/main.yml
- templates/etc/icinga2/conf.d/downtimes.conf.j2
This is a follow-up to #96.
Merely applying a ScheduledDowntime to `Host` is not sufficient; one still also needs to put all of that host's services into a downtime.
These changes create the `apply … to Service` directive in all cases.
If setting a host downtime (empty `services` attribute), we additionally create an `apply … to Host` directive and leave out the service matching in the `where` clauses.
https://community.icinga.com/t/recuring-downtime-for-host-and-its-services/779
Template test in Python:
```
>>> ….render(icinga2_master_downtimes = [
{'name': 'hoho',
'comment': 'some random comment',
'ranges': [{'day': 'monday', 'time': '01:00-02:00'},
{'day': 'tuesday', 'time': '01:00-02:00'}],
'hosts': ['hoho.tld'],
'services': ['svc_a', 'svc_b']},
{'name': 'hehe', …
```
> Put services in downtime also for full-host downtimes

- .github/workflows/ansible-ci.yml
Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>
The GH Action isn't working anymore. We saw this happening on other projects due to this PR on our ansible lint rules:
https://github.com/adfinis-sygroup/ansible-lint-rules/pull/4
https://github.com/adfinis-sygroup/ansible-lint-rules/pull/3
The rules now need ansible~=2.10 and ansible-lint ~=5.0
```
ansible 2.10
lint 5.0.0
```
```
```
> fix(ansible-lint): action with ansible 2.10 and lint 5.0

- defaults/main.yml
- templates/etc/icinga2/scripts/twilio-sms-host-notification.sh.j2
- templates/etc/icinga2/scripts/twilio-sms-service-notification.sh.j2
This commit allows users of the twilio sms feature to configure a
short url command which shortens the sms quite drastically.
For simplicity, the shorturl is configured trough an ansible variable
containing the command which gets the shortened url. There is probably
a nicer way to do this, but this was quite quick and easy and just works.
> implement short url capability

- tasks/configuration.yml
- vars/Debian.yml
- vars/Debian_11.yml
* use default-mysql-client to provide either mysql-client or mariadb-client instead of directly using mysql-client
* This could make it incompatible on ubuntu, maybe
* Provide a small fix so the folder for the icinga2_master_client_parent_zone  is always created
* The issue is in ansible itself, ansible cant set the selinux content when the directory does not already exist.
```
ansible [core 2.11.1]
```
> Fix debian support

- .github/workflows/galaxy-publish.yml
Add github actions workflow to publish role to ansible galaxy
> Add github actions workflow to publish role to ansible galaxy

- templates/etc/icinga2/scripts/twilio-sms-host-notification.sh.j2
- templates/etc/icinga2/scripts/twilio-sms-service-notification.sh.j2
In our environment, notification SMSes are sent to different users depending on the team to which a service is assigned *and* the team in which a user is.
We also send a copy of the SMS to other communication channels (e.g. Mattermost) for easier tracking/interaction, but in that case, all notifications (regardless of the assigned team) end up in the same place.
It would be nice to have a way to filter notifications by teams (or based on any other custom information). These changes implement a way to do so.
```
ansible [core 2.12.10]
configured module search path = ['/home/martinwe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3/dist-packages/ansible
ansible …
```
> Add option to pass additional/custom information to notification scripts

- templates/etc/icinga2/scripts/twilio-sms-host-notification.sh.j2
`-X` expects an argument, the help output should correctly reflect this (compare with `twilio-sms-service-notification`).
```
/usr/lib/python3/dist-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
"class": algorithms.Blowfish,
ansible [core 2.12.10]
configured module search path = ['/home/martinwe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3/dist-packages/ansible
ansible collection location = /home/martinwe/.ansible/collections:/usr/share/ansible/collections
python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
jinja version = 3.1.2
libyaml = True
``` …
> twilio-sms-host-notification: Add missing -X argument in help output

- README.md
- defaults/main.yml
- handlers/main.yml
- meta/main.yml
- tasks/configuration.yml
- tasks/installation.yml
- templates/etc/icinga2/conf.d/templates.conf.j2
- templates/etc/icinga2/constants.conf.j2
- templates/etc/icinga2/features-available/icingadb.conf.j2
- templates/etc/icinga2/features-available/ido-mysql.conf.j2
- templates/etc/icingadb-redis/icingadb-redis.conf.j2
- templates/etc/icingadb/config.yml.j2
- vars/Debian.yml
- vars/RedHat.yml
Fix various things to make the Playbook run on debian 12.
> feat: Debian12 readyness

- .github/workflows/ansible-ci.yml
- .github/workflows/galaxy-publish.yml
This PR improves the CI to make sure only releases are published to ansible galaxy. 
> ci: publish to galaxy on release only
