adfinis/ansible-role-icinga2_master

README.rst

migrated to travis-ci.com

---

defaults/main.yml
tasks/configuration.yml
templates/etc/icinga2/features-available/graphite.conf.j2

This pull request adds the ability to enable graphite for icinga2

implement graphite feature

---

README.rst

Hyperlinks in RST

---

tasks/configuration.yml

Task should only run when feature ido is enabled
```
```
```
```

run task only once and added feature constraint

---

tasks/configuration.yml

seems to have change in a recent release?!
```
```
```
```

fix selinux context

---

tasks/configuration.yml

cannot create our "own" host configuration if the directory isn't present, can't we?

reorder tasks

---

tasks/configuration.yml

fix piep fail

---

defaults/main.yml
tasks/configuration.yml

On azure, login happens from outside the local machine

make the login host pattern configurable

---

tasks/configuration.yml

same as in the icinga2_web role.

split user at @ and only use first part

---

templates/etc/icinga2/zones.d/generic_host.conf.j2

this allows to explicitly set the host address

fix icinga host address

---

tasks/configuration.yml

remove the hosts configuration as we create it later

---

tasks/configuration.yml
templates/etc/icinga2/zones.d/global-templates/hostgroups.conf.j2
templates/etc/icinga2/zones.d/global-templates/servicegroups.conf.j2

Adds the ability to managed host and servicegroups

implement service and hostgroups

---

defaults/main.yml
templates/etc/icinga2/conf.d/users.conf.j2

This PR massively extends the templating of icinga2 user and usergroups

Extend user and usergroups templating

---

tasks/configuration.yml

fix the groups.conf directory

---

templates/etc/icinga2/conf.d/users.conf.j2

set the group displayname from the displayname variable

---

defaults/main.yml

The example had the wrong variable name

fix variable name (typo)

---

defaults/main.yml
templates/etc/icinga2/conf.d/groups.conf.j2

This change allows us to configure the service and hostgroups through ansible

implement service and host groups

---

defaults/main.yml
templates/etc/icinga2/conf.d/commands.conf.j2

add mailfrom configuration option

---

README.rst
defaults/main.yml
tasks/configuration.yml

The provided templates do and should not cover every possible usecase and should be exchangeable. 

Make the templates user adjustable so they can be exchanged

---

tasks/configuration.yml

This makes them executable and allows for sms and phone calls to be sucessful

fix selinux context of nagios alerting scripts

---

templates/etc/icinga2/zones.d/global-templates/services.conf.j2

Adjust load values for lesser false positives
2.7
None

Adjust load values for lesser false positives

---

templates/etc/icinga2/zones.d/global-templates/services.conf.j2

Remove default values again, they can be overwritten in custom configs. It makes no sense to have them duplicated in multiple repos.
2.7
None

remove default values again, they can be overrwriten in custom configs

---

tasks/configuration.yml
templates/etc/icinga2/scripts/twilio-phone-notification.sh.j2
templates/etc/icinga2/scripts/twilio-sms-host-notification.sh.j2
templates/etc/icinga2/scripts/twilio-sms-service-notification.sh.j2

Cleanup twilio notification scripts to fix errors reported in the Icinga2 logs.

Cleanup twilio notification scripts

---

tasks/configuration.yml
tasks/installation.yml

ansible will disable interpreting bare variables in 2.12.
- Coding style

style(tasks): add bool filter to bare variables

---

templates/etc/icinga2/zones.d/generic_host.conf.j2

This change adds a new variable for hosts to disable notifications

add variable to disable notifications for a host

---

templates/etc/icinga2/zones.d/generic_host.conf.j2

This allows us to have comments for the hosts

implement notes for hosts

---

templates/etc/icinga2/conf.d/groups.conf.j2

Support wildcard matching in hostgroups template

Support wildcard matching in hostgroups template

---

templates/etc/icinga2/conf.d/groups.conf.j2

Fix undefined checks in groups.conf template

Fix undefined checks in groups.conf template

---

tasks/configuration.yml

Fix selinux types on icinga configuration

Fix selinux types on icinga configuration

---

defaults/main.yml
tasks/configuration.yml
templates/etc/icinga2/zones.conf.j2

- Support director managed hosts
- Backwards compatible

Director managed hosts

---

.github/workflows/ansible-ci.yml
defaults/main.yml

Fixing GitHub Actions

---

tasks/configuration.yml

Do not create host config if master is managed by director

Do not create host config if master is managed by director

---

defaults/main.yml
tasks/configuration.yml
templates/etc/icinga2/conf.d/api-users.conf.j2

Allow specifying advanced permissions with filters for api users

Allow specifying advanced permissions with filters for api users

---

defaults/main.yml
templates/etc/icinga2/conf.d/timeperiods.conf.j2

Make timeperiods configurable

---

templates/etc/icinga2/conf.d/api-users.conf.j2
templates/etc/icinga2/conf.d/templates.conf.j2

- Fix formatting in api-users.conf template
- Fix icinga url in templates.conf

Api users formatting

---

templates/etc/icinga2/scripts/twilio-sms-host-notification.sh.j2

The host sms had an issue with the wrong url which was introduced by copy pasta.

fix host url to icingaweb2

---

README.md
defaults/main.yml
templates/etc/icinga2/scripts/twilio-sms-host-notification.sh.j2
templates/etc/icinga2/scripts/twilio-sms-service-notification.sh.j2

* remove broken log line from sms scripts
* implement custom commands option for sms scripts

fix and extend sms scripts

---

.github/workflows/ansible-ci.yml
templates/etc/icinga2/scripts/twilio-sms-service-notification.sh.j2

This PR fixes a URL encoding issue that occurs since we replaced our URL shortener. I think previously the shortener did some URL magic so we never ran into this issue so far, but with the new solution the script generates invalid URLs. 

fix: correct url encoding when sending service alerts to twilio
